#define MAESTRO_RX 8
#define MAESTRO_TX 9

#define XBEE_RX 10
#define XBEE_TX 9

#define INPUT_SIZE 7

#define BAUD_RATE 38400

#define SETUP_DELAY_TIME  10000
#define EVENT_DELAY_TIME  100
#define TURRET_TILT_DELAY 10
#define TURRET_PAN_DELAY  10

#define MOVEMENT_THRESHOLD 15

#define FRONT_LEFT_HIP_HOME_POS    6204
#define FRONT_LEFT_KNEE_HOME_POS   4826
#define FRONT_LEFT_ANKLE_HOME_POS  8096
#define FRONT_RIGHT_HIP_HOME_POS   5494
#define FRONT_RIGHT_KNEE_HOME_POS  3392
#define FRONT_RIGHT_ANKLE_HOME_POS 7720
#define BACK_RIGHT_HIP_HOME_POS    7372
#define BACK_RIGHT_KNEE_HOME_POS   4024
#define BACK_RIGHT_ANKLE_HOME_POS  7630
#define BACK_LEFT_HIP_HOME_POS     4588
#define BACK_LEFT_KNEE_HOME_POS    3934
#define BACK_LEFT_ANKLE_HOME_POS   8722
#define TURRET_PAN_HOME_POS        6000
#define TURRET_TILT_HOME_POS       5850

#define CREEP_ROTATE_ANGLE       2000
#define CREEP_RAISE_KNEE_ANGLE   2000
#define CREEP_RAISE_ANKLE_ANGLE  1200
#define CREEP_PUSH_ANKLE_ANGLE   900
#define CREEP_PUSH_KNEE_ANGLE   -200
#define TURNING_V_ANGLE          800
#define TURNING_H_ANGLE          2000
#define TURRET_TILT_ANGLE        100
#define TURRET_PAN_LEFT_ANGLE    5000
#define TURRET_PAN_CENTER_ANGLE  6000
#define TURRET_PAN_RIGHT_ANGLE   7000
#define ZERO_ANGLE               0

#define HOME_STANCE_LEN           15
#define FRONT_STANCE_LEN          15
#define BACK_STANCE_LEN           15
#define RIGHT_STANCE_LEN          15
#define LEFT_STANCE_LEN           15
#define HOME_TO_CREEP_F_LEN       16
#define HOME_TO_CREEP_B_LEN       16
#define HOME_TO_CREEP_L_LEN       16
#define HOME_TO_CREEP_R_LEN       16
#define CREEP_FORWARD_FROM_R_LEN  24
#define CREEP_FORWARD_FROM_L_LEN  24
#define CREEP_BACKWARD_FROM_R_LEN 24
#define CREEP_BACKWARD_FROM_L_LEN 24
#define CREEP_LEFT_FROM_F_LEN     24
#define CREEP_LEFT_FROM_B_LEN     24
#define CREEP_RIGHT_FROM_F_LEN    24
#define CREEP_RIGHT_FROM_B_LEN    24
#define CREEP_F_TO_HOME_LEN       16
#define CREEP_B_TO_HOME_LEN       16
#define CREEP_L_TO_HOME_LEN       16
#define CREEP_R_TO_HOME_LEN       16
#define TURRET_V_LEN              6
#define TURRET_H_LEN              8
#define TURN_RIGHT_LEN            23
#define TURN_LEFT_LEN             23

enum stance_t {
    FRONT,
    BACK,
    RIGHT,
    LEFT,
    HOME
};

enum pservo_t {
    DELAY             = -1,
    FRONT_LEFT_HIP    = 0,
    FRONT_LEFT_KNEE   = 1,
    FRONT_LEFT_ANKLE  = 2,
    FRONT_RIGHT_HIP   = 3,
    FRONT_RIGHT_KNEE  = 4,
    FRONT_RIGHT_ANKLE = 5,
    BACK_RIGHT_HIP    = 6,
    BACK_RIGHT_KNEE   = 7,
    BACK_RIGHT_ANKLE  = 8,
    BACK_LEFT_HIP     = 9,
    BACK_LEFT_KNEE    = 10,
    BACK_LEFT_ANKLE   = 11,
    TURRET_PAN        = 12,
    TURRET_TILT       = 13,
    NUM_SERVOS        = 14
};

struct event_t {
    pservo_t servo;
    int value;
};

int HOME_POS[] = {
    [FRONT_LEFT_HIP]    = FRONT_LEFT_HIP_HOME_POS,
    [FRONT_LEFT_KNEE]   = FRONT_LEFT_KNEE_HOME_POS,
    [FRONT_LEFT_ANKLE]  = FRONT_LEFT_ANKLE_HOME_POS,
    [FRONT_RIGHT_HIP]   = FRONT_RIGHT_HIP_HOME_POS,
    [FRONT_RIGHT_KNEE]  = FRONT_RIGHT_KNEE_HOME_POS,
    [FRONT_RIGHT_ANKLE] = FRONT_RIGHT_ANKLE_HOME_POS,
    [BACK_RIGHT_HIP]    = BACK_RIGHT_HIP_HOME_POS,
    [BACK_RIGHT_KNEE]   = BACK_RIGHT_KNEE_HOME_POS,
    [BACK_RIGHT_ANKLE]  = BACK_RIGHT_ANKLE_HOME_POS,
    [BACK_LEFT_HIP]     = BACK_LEFT_HIP_HOME_POS,
    [BACK_LEFT_KNEE]    = BACK_LEFT_KNEE_HOME_POS,
    [BACK_LEFT_ANKLE]   = BACK_LEFT_ANKLE_HOME_POS,
    [TURRET_PAN]        = TURRET_PAN_HOME_POS,
    [TURRET_TILT]       = TURRET_TILT_HOME_POS
};

event_t HOME_STANCE[] = {
    {FRONT_RIGHT_HIP,   ZERO_ANGLE},
    {FRONT_RIGHT_KNEE,  ZERO_ANGLE},
    {FRONT_RIGHT_ANKLE, ZERO_ANGLE},
    {FRONT_LEFT_HIP,    ZERO_ANGLE},
    {FRONT_LEFT_KNEE,   ZERO_ANGLE},
    {FRONT_LEFT_ANKLE,  ZERO_ANGLE},
    {BACK_RIGHT_HIP,    ZERO_ANGLE},
    {BACK_RIGHT_KNEE,   ZERO_ANGLE},
    {BACK_RIGHT_ANKLE,  ZERO_ANGLE},
    {BACK_LEFT_HIP,     ZERO_ANGLE},
    {BACK_LEFT_KNEE,    ZERO_ANGLE},
    {BACK_LEFT_ANKLE,   ZERO_ANGLE},
    {TURRET_PAN,        ZERO_ANGLE},
    {TURRET_TILT,       ZERO_ANGLE},
    {DELAY,             EVENT_DELAY_TIME}
};

event_t FRONT_STANCE[] = {
    {FRONT_RIGHT_HIP,   -CREEP_ROTATE_ANGLE},
    {FRONT_RIGHT_KNEE,  ZERO_ANGLE},
    {FRONT_RIGHT_ANKLE, ZERO_ANGLE},
    {FRONT_LEFT_HIP,    -CREEP_ROTATE_ANGLE},
    {FRONT_LEFT_KNEE,   ZERO_ANGLE},
    {FRONT_LEFT_ANKLE,  ZERO_ANGLE},
    {BACK_RIGHT_HIP,    ZERO_ANGLE},
    {BACK_RIGHT_KNEE,   ZERO_ANGLE},
    {BACK_RIGHT_ANKLE,  ZERO_ANGLE},
    {BACK_LEFT_HIP,     ZERO_ANGLE},
    {BACK_LEFT_KNEE,    ZERO_ANGLE},
    {BACK_LEFT_ANKLE,   ZERO_ANGLE},
    {TURRET_PAN,        ZERO_ANGLE},
    {TURRET_TILT,       ZERO_ANGLE},
    {DELAY,             EVENT_DELAY_TIME}
};

event_t BACK_STANCE[] = {
    {FRONT_RIGHT_HIP,   ZERO_ANGLE},
    {FRONT_RIGHT_KNEE,  ZERO_ANGLE},
    {FRONT_RIGHT_ANKLE, ZERO_ANGLE},
    {FRONT_LEFT_HIP,    ZERO_ANGLE},
    {FRONT_LEFT_KNEE,   ZERO_ANGLE},
    {FRONT_LEFT_ANKLE,  ZERO_ANGLE},
    {BACK_RIGHT_HIP,    CREEP_ROTATE_ANGLE},
    {BACK_RIGHT_KNEE,   ZERO_ANGLE},
    {BACK_RIGHT_ANKLE,  ZERO_ANGLE},
    {BACK_LEFT_HIP,     CREEP_ROTATE_ANGLE},
    {BACK_LEFT_KNEE,    ZERO_ANGLE},
    {BACK_LEFT_ANKLE,   ZERO_ANGLE},
    {TURRET_PAN,        ZERO_ANGLE},
    {TURRET_TILT,       ZERO_ANGLE},
    {DELAY,             EVENT_DELAY_TIME}
};

event_t LEFT_STANCE[] = {
    {FRONT_RIGHT_HIP,   CREEP_ROTATE_ANGLE},
    {FRONT_RIGHT_KNEE,  ZERO_ANGLE},
    {FRONT_RIGHT_ANKLE, ZERO_ANGLE},
    {FRONT_LEFT_HIP,    ZERO_ANGLE},
    {FRONT_LEFT_KNEE,   ZERO_ANGLE},
    {FRONT_LEFT_ANKLE,  ZERO_ANGLE},
    {BACK_RIGHT_HIP,    ZERO_ANGLE},
    {BACK_RIGHT_KNEE,   ZERO_ANGLE},
    {BACK_RIGHT_ANKLE,  ZERO_ANGLE},
    {BACK_LEFT_HIP,     -CREEP_ROTATE_ANGLE},
    {BACK_LEFT_KNEE,    ZERO_ANGLE},
    {BACK_LEFT_ANKLE,   ZERO_ANGLE},
    {TURRET_PAN,        ZERO_ANGLE},
    {TURRET_TILT,       ZERO_ANGLE},
    {DELAY,             EVENT_DELAY_TIME}
};

event_t RIGHT_STANCE[] = {
    {FRONT_RIGHT_HIP,   ZERO_ANGLE},
    {FRONT_RIGHT_KNEE,  ZERO_ANGLE},
    {FRONT_RIGHT_ANKLE, ZERO_ANGLE},
    {FRONT_LEFT_HIP,    CREEP_ROTATE_ANGLE},
    {FRONT_LEFT_KNEE,   ZERO_ANGLE},
    {FRONT_LEFT_ANKLE,  ZERO_ANGLE},
    {BACK_RIGHT_HIP,    -CREEP_ROTATE_ANGLE},
    {BACK_RIGHT_KNEE,   ZERO_ANGLE},
    {BACK_RIGHT_ANKLE,  ZERO_ANGLE},
    {BACK_LEFT_HIP,     ZERO_ANGLE},
    {BACK_LEFT_KNEE,    ZERO_ANGLE},
    {BACK_LEFT_ANKLE,   ZERO_ANGLE},
    {TURRET_PAN,        ZERO_ANGLE},
    {TURRET_TILT,       ZERO_ANGLE},
    {DELAY,             EVENT_DELAY_TIME}
};


event_t HOME_TO_CREEP_F[] = {
    {FRONT_LEFT_KNEE,   CREEP_RAISE_KNEE_ANGLE},
    {FRONT_LEFT_ANKLE,  CREEP_RAISE_ANKLE_ANGLE},
    {DELAY,             EVENT_DELAY_TIME},
    {FRONT_LEFT_HIP,   -CREEP_ROTATE_ANGLE},
    {DELAY,             EVENT_DELAY_TIME},
    {FRONT_LEFT_KNEE,   ZERO_ANGLE},
    {FRONT_LEFT_ANKLE,  ZERO_ANGLE},
    {DELAY,             EVENT_DELAY_TIME},
    {FRONT_RIGHT_KNEE,    CREEP_RAISE_KNEE_ANGLE},
    {FRONT_RIGHT_ANKLE,   CREEP_RAISE_ANKLE_ANGLE},
    {DELAY,             EVENT_DELAY_TIME},
    {FRONT_RIGHT_HIP,     -CREEP_ROTATE_ANGLE},
    {DELAY,             EVENT_DELAY_TIME},
    {FRONT_RIGHT_KNEE,    ZERO_ANGLE},
    {FRONT_RIGHT_ANKLE,   ZERO_ANGLE},
    {DELAY,             EVENT_DELAY_TIME}

};

event_t HOME_TO_CREEP_B[] = {
    {BACK_LEFT_KNEE,   CREEP_RAISE_KNEE_ANGLE},
    {BACK_LEFT_ANKLE,  CREEP_RAISE_ANKLE_ANGLE},
    {DELAY,             EVENT_DELAY_TIME},
    {BACK_LEFT_HIP,   CREEP_ROTATE_ANGLE},
    {DELAY,             EVENT_DELAY_TIME},
    {BACK_LEFT_KNEE,   ZERO_ANGLE},
    {BACK_LEFT_ANKLE,  ZERO_ANGLE},
    {DELAY,             EVENT_DELAY_TIME},
    {BACK_RIGHT_KNEE,    CREEP_RAISE_KNEE_ANGLE},
    {BACK_RIGHT_ANKLE,   CREEP_RAISE_ANKLE_ANGLE},
    {DELAY,             EVENT_DELAY_TIME},
    {BACK_RIGHT_HIP,     CREEP_ROTATE_ANGLE},
    {DELAY,             EVENT_DELAY_TIME},
    {BACK_RIGHT_KNEE,    ZERO_ANGLE},
    {BACK_RIGHT_ANKLE,   ZERO_ANGLE},
    {DELAY,             EVENT_DELAY_TIME}

};

event_t HOME_TO_CREEP_L[] = {
    {FRONT_LEFT_KNEE,   CREEP_RAISE_KNEE_ANGLE},
    {FRONT_LEFT_ANKLE,  CREEP_RAISE_ANKLE_ANGLE},
    {DELAY,             EVENT_DELAY_TIME},
    {FRONT_LEFT_HIP,   -CREEP_ROTATE_ANGLE},
    {DELAY,             EVENT_DELAY_TIME},
    {FRONT_LEFT_KNEE,   ZERO_ANGLE},
    {FRONT_LEFT_ANKLE,  ZERO_ANGLE},
    {DELAY,             EVENT_DELAY_TIME},
    {BACK_LEFT_KNEE,    CREEP_RAISE_KNEE_ANGLE},
    {BACK_LEFT_ANKLE,   CREEP_RAISE_ANKLE_ANGLE},
    {DELAY,             EVENT_DELAY_TIME},
    {BACK_LEFT_HIP,     CREEP_ROTATE_ANGLE},
    {DELAY,             EVENT_DELAY_TIME},
    {BACK_LEFT_KNEE,    ZERO_ANGLE},
    {BACK_LEFT_ANKLE,   ZERO_ANGLE},
    {DELAY,             EVENT_DELAY_TIME}
};

event_t HOME_TO_CREEP_R[] = {
    {FRONT_RIGHT_KNEE,   CREEP_RAISE_KNEE_ANGLE},
    {FRONT_RIGHT_ANKLE,  CREEP_RAISE_ANKLE_ANGLE},
    {DELAY,              EVENT_DELAY_TIME},
    {FRONT_RIGHT_HIP,    CREEP_ROTATE_ANGLE},
    {DELAY,              EVENT_DELAY_TIME},
    {FRONT_RIGHT_KNEE,   ZERO_ANGLE},
    {FRONT_RIGHT_ANKLE,  ZERO_ANGLE},
    {DELAY,              EVENT_DELAY_TIME},
    {BACK_RIGHT_KNEE,    CREEP_RAISE_KNEE_ANGLE},
    {BACK_RIGHT_ANKLE,   CREEP_RAISE_ANKLE_ANGLE},
    {DELAY,              EVENT_DELAY_TIME},
    {BACK_RIGHT_HIP,    -CREEP_ROTATE_ANGLE},
    {DELAY,              EVENT_DELAY_TIME},
    {BACK_RIGHT_KNEE,    ZERO_ANGLE},
    {BACK_RIGHT_ANKLE,   ZERO_ANGLE},
    {DELAY,              EVENT_DELAY_TIME}
};

event_t CREEP_FORWARD_FROM_R[] = {
    {TURRET_PAN,         ZERO_ANGLE},
    {TURRET_TILT,        ZERO_ANGLE},
    {FRONT_RIGHT_KNEE,   CREEP_RAISE_KNEE_ANGLE},
    {FRONT_RIGHT_ANKLE, -CREEP_PUSH_ANKLE_ANGLE},
    {DELAY,              EVENT_DELAY_TIME},
    {FRONT_RIGHT_HIP,    ZERO_ANGLE},
    {DELAY,              EVENT_DELAY_TIME},
    {FRONT_RIGHT_KNEE,   CREEP_PUSH_KNEE_ANGLE},
    {FRONT_RIGHT_ANKLE, -CREEP_PUSH_ANKLE_ANGLE},
    {DELAY,              EVENT_DELAY_TIME},
    {BACK_RIGHT_HIP,     ZERO_ANGLE},
    {FRONT_LEFT_HIP,    -CREEP_ROTATE_ANGLE},
    {BACK_LEFT_ANKLE,   -CREEP_PUSH_ANKLE_ANGLE},
    {FRONT_RIGHT_KNEE,   ZERO_ANGLE},
    {FRONT_RIGHT_ANKLE,  ZERO_ANGLE},
    {DELAY,              EVENT_DELAY_TIME},
    {BACK_LEFT_KNEE,     CREEP_RAISE_KNEE_ANGLE},
    {BACK_LEFT_ANKLE,    CREEP_RAISE_ANKLE_ANGLE},
    {DELAY,              EVENT_DELAY_TIME},
    {BACK_LEFT_HIP,      CREEP_ROTATE_ANGLE},
    {DELAY,              EVENT_DELAY_TIME},
    {BACK_LEFT_KNEE,     ZERO_ANGLE},
    {BACK_LEFT_ANKLE,    ZERO_ANGLE},
    {DELAY,              EVENT_DELAY_TIME}

};

event_t CREEP_FORWARD_FROM_L[] = {
    {TURRET_PAN,        ZERO_ANGLE},
    {TURRET_TILT,       ZERO_ANGLE},
    {FRONT_LEFT_KNEE,   CREEP_RAISE_KNEE_ANGLE},
    {FRONT_LEFT_ANKLE, -CREEP_PUSH_ANKLE_ANGLE},
    {DELAY,             EVENT_DELAY_TIME},
    {FRONT_LEFT_HIP,    ZERO_ANGLE},
    {DELAY,             EVENT_DELAY_TIME},
    {FRONT_LEFT_KNEE,   CREEP_PUSH_KNEE_ANGLE},
    {FRONT_LEFT_ANKLE, -CREEP_PUSH_ANKLE_ANGLE},
    {DELAY,             EVENT_DELAY_TIME},
    {BACK_LEFT_HIP,     ZERO_ANGLE},
    {FRONT_RIGHT_HIP,   CREEP_ROTATE_ANGLE},
    {BACK_RIGHT_ANKLE, -CREEP_PUSH_ANKLE_ANGLE},
    {FRONT_LEFT_KNEE,   ZERO_ANGLE},
    {FRONT_LEFT_ANKLE,  ZERO_ANGLE},
    {DELAY,             EVENT_DELAY_TIME},
    {BACK_RIGHT_KNEE,   CREEP_RAISE_KNEE_ANGLE},
    {BACK_RIGHT_ANKLE,  CREEP_RAISE_ANKLE_ANGLE},
    {DELAY,             EVENT_DELAY_TIME},
    {BACK_RIGHT_HIP,   -CREEP_ROTATE_ANGLE},
    {DELAY,             EVENT_DELAY_TIME},
    {BACK_RIGHT_KNEE,   ZERO_ANGLE},
    {BACK_RIGHT_ANKLE,  ZERO_ANGLE},
    {DELAY,             EVENT_DELAY_TIME}
};

event_t CREEP_BACKWARD_FROM_R[] = {
    {TURRET_PAN,        ZERO_ANGLE},
    {TURRET_TILT,       ZERO_ANGLE},
    {BACK_RIGHT_KNEE,   CREEP_RAISE_KNEE_ANGLE},
    {BACK_RIGHT_ANKLE, -CREEP_PUSH_ANKLE_ANGLE},
    {DELAY,             EVENT_DELAY_TIME},
    {BACK_RIGHT_HIP,    ZERO_ANGLE},
    {DELAY,             EVENT_DELAY_TIME},
    {BACK_RIGHT_KNEE,   CREEP_PUSH_KNEE_ANGLE},
    {BACK_RIGHT_ANKLE, -CREEP_PUSH_ANKLE_ANGLE},
    {DELAY,             EVENT_DELAY_TIME},
    {FRONT_RIGHT_HIP,   ZERO_ANGLE},
    {BACK_LEFT_HIP,     CREEP_ROTATE_ANGLE},
    {FRONT_LEFT_ANKLE, -CREEP_PUSH_ANKLE_ANGLE},
    {BACK_RIGHT_KNEE,   ZERO_ANGLE},
    {BACK_RIGHT_ANKLE,  ZERO_ANGLE},
    {DELAY,             EVENT_DELAY_TIME},
    {FRONT_LEFT_KNEE,   CREEP_RAISE_KNEE_ANGLE},
    {FRONT_LEFT_ANKLE,  CREEP_RAISE_ANKLE_ANGLE},
    {DELAY,             EVENT_DELAY_TIME},
    {FRONT_LEFT_HIP,   -CREEP_ROTATE_ANGLE},
    {DELAY,             EVENT_DELAY_TIME},
    {FRONT_LEFT_KNEE,   ZERO_ANGLE},
    {FRONT_LEFT_ANKLE,  ZERO_ANGLE},
    {DELAY,             EVENT_DELAY_TIME}

};

event_t CREEP_BACKWARD_FROM_L[] = {
    {TURRET_PAN,         ZERO_ANGLE},
    {TURRET_TILT,        ZERO_ANGLE},
    {BACK_LEFT_KNEE,     CREEP_RAISE_KNEE_ANGLE},
    {BACK_LEFT_ANKLE,   -CREEP_PUSH_ANKLE_ANGLE},
    {DELAY,              EVENT_DELAY_TIME},
    {BACK_LEFT_HIP,      ZERO_ANGLE},
    {DELAY,              EVENT_DELAY_TIME},
    {BACK_LEFT_KNEE,     CREEP_PUSH_KNEE_ANGLE},
    {BACK_LEFT_ANKLE,   -CREEP_PUSH_ANKLE_ANGLE},
    {DELAY,              EVENT_DELAY_TIME},
    {FRONT_LEFT_HIP,     ZERO_ANGLE},
    {BACK_RIGHT_HIP,    -CREEP_ROTATE_ANGLE},
    {FRONT_RIGHT_ANKLE, -CREEP_PUSH_ANKLE_ANGLE},
    {BACK_LEFT_KNEE,     ZERO_ANGLE},
    {BACK_LEFT_ANKLE,    ZERO_ANGLE},
    {DELAY,              EVENT_DELAY_TIME},
    {FRONT_RIGHT_KNEE,   CREEP_RAISE_KNEE_ANGLE},
    {FRONT_RIGHT_ANKLE,  CREEP_RAISE_ANKLE_ANGLE},
    {DELAY,              EVENT_DELAY_TIME},
    {FRONT_RIGHT_HIP,    CREEP_ROTATE_ANGLE},
    {DELAY,              EVENT_DELAY_TIME},
    {FRONT_RIGHT_KNEE,   ZERO_ANGLE},
    {FRONT_RIGHT_ANKLE,  ZERO_ANGLE},
    {DELAY,              EVENT_DELAY_TIME}
};

event_t CREEP_LEFT_FROM_F[] = {
    {TURRET_PAN,         ZERO_ANGLE},
    {TURRET_TILT,        ZERO_ANGLE},
    {FRONT_LEFT_KNEE,    CREEP_RAISE_KNEE_ANGLE},
    {FRONT_LEFT_ANKLE,  -CREEP_PUSH_ANKLE_ANGLE},
    {DELAY,              EVENT_DELAY_TIME},
    {FRONT_LEFT_HIP,     ZERO_ANGLE},
    {DELAY,              EVENT_DELAY_TIME},
    {FRONT_LEFT_KNEE,    CREEP_PUSH_KNEE_ANGLE},
    {FRONT_LEFT_ANKLE,  -CREEP_PUSH_ANKLE_ANGLE},
    {DELAY,              EVENT_DELAY_TIME},
    {FRONT_RIGHT_HIP,    ZERO_ANGLE},
    {BACK_LEFT_HIP,      CREEP_ROTATE_ANGLE},
    {FRONT_RIGHT_ANKLE, -CREEP_PUSH_ANKLE_ANGLE},
    {FRONT_LEFT_KNEE,    ZERO_ANGLE},
    {FRONT_LEFT_ANKLE,   ZERO_ANGLE},
    {DELAY,              EVENT_DELAY_TIME},
    {BACK_RIGHT_KNEE,    CREEP_RAISE_KNEE_ANGLE},
    {BACK_RIGHT_ANKLE,   CREEP_RAISE_ANKLE_ANGLE},
    {DELAY,              EVENT_DELAY_TIME},
    {BACK_RIGHT_HIP,     CREEP_ROTATE_ANGLE},
    {DELAY,              EVENT_DELAY_TIME},
    {BACK_RIGHT_KNEE,    ZERO_ANGLE},
    {BACK_RIGHT_ANKLE,   ZERO_ANGLE},
    {DELAY,              EVENT_DELAY_TIME}

};

event_t CREEP_LEFT_FROM_B[] = {
    {TURRET_PAN,        ZERO_ANGLE},
    {TURRET_TILT,       ZERO_ANGLE},
    {BACK_LEFT_KNEE,    CREEP_RAISE_KNEE_ANGLE},
    {BACK_LEFT_ANKLE,  -CREEP_PUSH_ANKLE_ANGLE},
    {DELAY,             EVENT_DELAY_TIME},
    {BACK_LEFT_HIP,     ZERO_ANGLE},
    {DELAY,             EVENT_DELAY_TIME},
    {BACK_LEFT_KNEE,    CREEP_PUSH_KNEE_ANGLE},
    {BACK_LEFT_ANKLE,  -CREEP_PUSH_ANKLE_ANGLE},
    {DELAY,             EVENT_DELAY_TIME},
    {BACK_RIGHT_HIP,    ZERO_ANGLE},
    {BACK_LEFT_HIP,    -CREEP_ROTATE_ANGLE},
    {BACK_RIGHT_ANKLE, -CREEP_PUSH_ANKLE_ANGLE},
    {BACK_LEFT_KNEE,    ZERO_ANGLE},
    {BACK_LEFT_ANKLE,   ZERO_ANGLE},
    {DELAY,             EVENT_DELAY_TIME},
    {FRONT_RIGHT_KNEE,  CREEP_RAISE_KNEE_ANGLE},
    {FRONT_RIGHT_ANKLE, CREEP_RAISE_ANKLE_ANGLE},
    {DELAY,             EVENT_DELAY_TIME},
    {FRONT_RIGHT_HIP,  -CREEP_ROTATE_ANGLE},
    {DELAY,             EVENT_DELAY_TIME},
    {FRONT_RIGHT_KNEE,  ZERO_ANGLE},
    {FRONT_RIGHT_ANKLE, ZERO_ANGLE},
    {DELAY,             EVENT_DELAY_TIME}

};

event_t CREEP_RIGHT_FROM_F[] = {
    {TURRET_PAN,         ZERO_ANGLE},
    {TURRET_TILT,        ZERO_ANGLE},
    {FRONT_RIGHT_KNEE,    CREEP_RAISE_KNEE_ANGLE},
    {FRONT_RIGHT_ANKLE,  -CREEP_PUSH_ANKLE_ANGLE},
    {DELAY,              EVENT_DELAY_TIME},
    {FRONT_RIGHT_HIP,     ZERO_ANGLE},
    {DELAY,              EVENT_DELAY_TIME},
    {FRONT_RIGHT_KNEE,    CREEP_PUSH_KNEE_ANGLE},
    {FRONT_RIGHT_ANKLE,  -CREEP_PUSH_ANKLE_ANGLE},
    {DELAY,              EVENT_DELAY_TIME},
    {FRONT_LEFT_HIP,    ZERO_ANGLE},
    {BACK_RIGHT_HIP,      CREEP_ROTATE_ANGLE},
    {FRONT_LEFT_ANKLE, -CREEP_PUSH_ANKLE_ANGLE},
    {FRONT_RIGHT_KNEE,    ZERO_ANGLE},
    {FRONT_RIGHT_ANKLE,   ZERO_ANGLE},
    {DELAY,              EVENT_DELAY_TIME},
    {BACK_LEFT_KNEE,    CREEP_RAISE_KNEE_ANGLE},
    {BACK_LEFT_ANKLE,   CREEP_RAISE_ANKLE_ANGLE},
    {DELAY,              EVENT_DELAY_TIME},
    {BACK_LEFT_HIP,     CREEP_ROTATE_ANGLE},
    {DELAY,              EVENT_DELAY_TIME},
    {BACK_LEFT_KNEE,    ZERO_ANGLE},
    {BACK_LEFT_ANKLE,   ZERO_ANGLE},
    {DELAY,              EVENT_DELAY_TIME}

};

event_t CREEP_RIGHT_FROM_B[] = {
    {TURRET_PAN,        ZERO_ANGLE},
    {TURRET_TILT,       ZERO_ANGLE},
    {BACK_RIGHT_KNEE,    CREEP_RAISE_KNEE_ANGLE},
    {BACK_RIGHT_ANKLE,  -CREEP_PUSH_ANKLE_ANGLE},
    {DELAY,             EVENT_DELAY_TIME},
    {BACK_RIGHT_HIP,     ZERO_ANGLE},
    {DELAY,             EVENT_DELAY_TIME},
    {BACK_RIGHT_KNEE,    CREEP_PUSH_KNEE_ANGLE},
    {BACK_RIGHT_ANKLE,  -CREEP_PUSH_ANKLE_ANGLE},
    {DELAY,             EVENT_DELAY_TIME},
    {BACK_LEFT_HIP,    ZERO_ANGLE},
    {BACK_RIGHT_HIP,    -CREEP_ROTATE_ANGLE},
    {BACK_LEFT_ANKLE, -CREEP_PUSH_ANKLE_ANGLE},
    {BACK_RIGHT_KNEE,    ZERO_ANGLE},
    {BACK_RIGHT_ANKLE,   ZERO_ANGLE},
    {DELAY,             EVENT_DELAY_TIME},
    {FRONT_LEFT_KNEE,  CREEP_RAISE_KNEE_ANGLE},
    {FRONT_LEFT_ANKLE, CREEP_RAISE_ANKLE_ANGLE},
    {DELAY,             EVENT_DELAY_TIME},
    {FRONT_LEFT_HIP,  -CREEP_ROTATE_ANGLE},
    {DELAY,             EVENT_DELAY_TIME},
    {FRONT_LEFT_KNEE,  ZERO_ANGLE},
    {FRONT_LEFT_ANKLE, ZERO_ANGLE},
    {DELAY,             EVENT_DELAY_TIME}

};

event_t CREEP_F_TO_HOME[] = {
  {FRONT_LEFT_KNEE,   CREEP_RAISE_KNEE_ANGLE},
  {FRONT_LEFT_ANKLE,  CREEP_RAISE_ANKLE_ANGLE},
  {DELAY,            EVENT_DELAY_TIME},
  {FRONT_LEFT_HIP,    ZERO_ANGLE},
  {DELAY,            EVENT_DELAY_TIME},
  {FRONT_LEFT_KNEE,   ZERO_ANGLE},
  {FRONT_LEFT_ANKLE,  ZERO_ANGLE},
  {DELAY,            EVENT_DELAY_TIME},
  {FRONT_RIGHT_KNEE,   CREEP_RAISE_KNEE_ANGLE},
  {FRONT_RIGHT_ANKLE,  CREEP_RAISE_ANKLE_ANGLE},
  {DELAY,            EVENT_DELAY_TIME},
  {FRONT_RIGHT_HIP,    ZERO_ANGLE},
  {DELAY,            EVENT_DELAY_TIME},
  {FRONT_RIGHT_KNEE,   ZERO_ANGLE},
  {FRONT_RIGHT_ANKLE,  ZERO_ANGLE},
  {DELAY,            EVENT_DELAY_TIME}


};

event_t CREEP_B_TO_HOME[] = {
  {BACK_LEFT_KNEE,   CREEP_RAISE_KNEE_ANGLE},
  {BACK_LEFT_ANKLE,  CREEP_RAISE_ANKLE_ANGLE},
  {DELAY,            EVENT_DELAY_TIME},
  {BACK_LEFT_HIP,    ZERO_ANGLE},
  {DELAY,            EVENT_DELAY_TIME},
  {BACK_LEFT_KNEE,   ZERO_ANGLE},
  {BACK_LEFT_ANKLE,  ZERO_ANGLE},
  {DELAY,            EVENT_DELAY_TIME},
  {BACK_RIGHT_KNEE,   CREEP_RAISE_KNEE_ANGLE},
  {BACK_RIGHT_ANKLE,  CREEP_RAISE_ANKLE_ANGLE},
  {DELAY,            EVENT_DELAY_TIME},
  {BACK_RIGHT_HIP,    ZERO_ANGLE},
  {DELAY,            EVENT_DELAY_TIME},
  {BACK_RIGHT_KNEE,   ZERO_ANGLE},
  {BACK_RIGHT_ANKLE,  ZERO_ANGLE},
  {DELAY,            EVENT_DELAY_TIME}

};

event_t CREEP_L_TO_HOME[] = {
    {FRONT_LEFT_KNEE,  CREEP_RAISE_KNEE_ANGLE},
    {FRONT_LEFT_ANKLE, CREEP_RAISE_ANKLE_ANGLE},
    {DELAY,            EVENT_DELAY_TIME},
    {FRONT_LEFT_HIP,   ZERO_ANGLE},
    {DELAY,            EVENT_DELAY_TIME},
    {FRONT_LEFT_KNEE,  ZERO_ANGLE},
    {FRONT_LEFT_ANKLE, ZERO_ANGLE},
    {DELAY,            EVENT_DELAY_TIME},
    {BACK_LEFT_KNEE,   CREEP_RAISE_KNEE_ANGLE},
    {BACK_LEFT_ANKLE,  CREEP_RAISE_ANKLE_ANGLE},
    {DELAY,            EVENT_DELAY_TIME},
    {BACK_LEFT_HIP,    ZERO_ANGLE},
    {DELAY,            EVENT_DELAY_TIME},
    {BACK_LEFT_KNEE,   ZERO_ANGLE},
    {BACK_LEFT_ANKLE,  ZERO_ANGLE},
    {DELAY,            EVENT_DELAY_TIME}
};

event_t CREEP_R_TO_HOME[] = {
    {FRONT_RIGHT_KNEE,  CREEP_RAISE_KNEE_ANGLE},
    {FRONT_RIGHT_ANKLE, CREEP_RAISE_ANKLE_ANGLE},
    {DELAY,             EVENT_DELAY_TIME},
    {FRONT_RIGHT_HIP,   ZERO_ANGLE},
    {DELAY,             EVENT_DELAY_TIME},
    {FRONT_RIGHT_KNEE,  ZERO_ANGLE},
    {FRONT_RIGHT_ANKLE, ZERO_ANGLE},
    {DELAY,             EVENT_DELAY_TIME},
    {BACK_RIGHT_KNEE,   CREEP_RAISE_KNEE_ANGLE},
    {BACK_RIGHT_ANKLE,  CREEP_RAISE_ANKLE_ANGLE},
    {DELAY,             EVENT_DELAY_TIME},
    {BACK_RIGHT_HIP,    ZERO_ANGLE},
    {DELAY,             EVENT_DELAY_TIME},
    {BACK_RIGHT_KNEE,   ZERO_ANGLE},
    {BACK_RIGHT_ANKLE,  ZERO_ANGLE},
    {DELAY,             EVENT_DELAY_TIME}
};

event_t TURRET_V[] = {
    {TURRET_TILT,   700},
    {DELAY,         1000},
    {TURRET_TILT,  -700},
    {DELAY,         1000},
    {TURRET_TILT,   0},
    {DELAY,         1000}
};

event_t TURRET_H[] = {
    {TURRET_PAN,   1000},
    {DELAY,        300},
    {TURRET_PAN,  -1000},
    {DELAY,        600},
    {TURRET_PAN,   1000},
    {DELAY,        355},
    {TURRET_PAN,   0},
    {DELAY,        300}
};

event_t TURN_RIGHT[] = {
    {FRONT_LEFT_KNEE,  TURNING_V_ANGLE},
    {BACK_RIGHT_KNEE,  TURNING_V_ANGLE},
    {DELAY,            EVENT_DELAY_TIME},
    {FRONT_LEFT_HIP,  -TURNING_H_ANGLE},
    {BACK_RIGHT_HIP,  -TURNING_H_ANGLE},
    {DELAY,            EVENT_DELAY_TIME},
    {FRONT_LEFT_KNEE,  ZERO_ANGLE},
    {BACK_RIGHT_KNEE,  ZERO_ANGLE},
    {DELAY,            EVENT_DELAY_TIME},
    {FRONT_LEFT_HIP,   ZERO_ANGLE},
    {BACK_RIGHT_HIP,   ZERO_ANGLE},

    {FRONT_RIGHT_KNEE,  TURNING_V_ANGLE},
    {BACK_LEFT_KNEE,    TURNING_V_ANGLE},
    {DELAY,             EVENT_DELAY_TIME},
    {FRONT_RIGHT_HIP,  -TURNING_H_ANGLE},
    {BACK_LEFT_HIP,    -TURNING_H_ANGLE},
    {DELAY,             EVENT_DELAY_TIME},
    {FRONT_RIGHT_KNEE,  ZERO_ANGLE},
    {BACK_LEFT_KNEE,    ZERO_ANGLE},
    {DELAY,             EVENT_DELAY_TIME},
    {FRONT_RIGHT_HIP,   ZERO_ANGLE},
    {BACK_LEFT_HIP,     ZERO_ANGLE},
};

event_t TURN_LEFT[] = {
    {FRONT_LEFT_KNEE, TURNING_V_ANGLE},
    {BACK_RIGHT_KNEE, TURNING_V_ANGLE},
    {DELAY,           EVENT_DELAY_TIME},
    {FRONT_LEFT_HIP,  TURNING_H_ANGLE},
    {BACK_RIGHT_HIP,  TURNING_H_ANGLE},
    {DELAY,           EVENT_DELAY_TIME},
    {FRONT_LEFT_KNEE, ZERO_ANGLE},
    {BACK_RIGHT_KNEE, ZERO_ANGLE},
    {DELAY,           EVENT_DELAY_TIME},
    {FRONT_LEFT_HIP,  ZERO_ANGLE},
    {BACK_RIGHT_HIP,  ZERO_ANGLE},

    {FRONT_RIGHT_KNEE, TURNING_V_ANGLE},
    {BACK_LEFT_KNEE,   TURNING_V_ANGLE},
    {DELAY,            EVENT_DELAY_TIME},
    {FRONT_RIGHT_HIP,  TURNING_H_ANGLE},
    {BACK_LEFT_HIP,    TURNING_H_ANGLE},
    {DELAY,            EVENT_DELAY_TIME},
    {FRONT_RIGHT_KNEE, ZERO_ANGLE},
    {BACK_LEFT_KNEE,   ZERO_ANGLE},
    {DELAY,            EVENT_DELAY_TIME},
    {FRONT_RIGHT_HIP,  ZERO_ANGLE},
    {BACK_LEFT_HIP,    ZERO_ANGLE}
};
